config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]
 
 resources :topics do
     resources :posts, except: [:index], controller: 'topics/posts' do
      resources :summaries, except: [:index]
    end
  end

   resources :posts, only: [:index] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
 
   end

 get 'about' => 'welcome#about'
  root to: 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  default_scope { order('rank DESC')} #we got this by doing generate migration AddRankToPosts
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true)}
    # joins basically takes all posts for WHERE a topic is public
    # read up on the rails guide to active record to do SQL queries via ACtiveRecord
    # then go apply visible_to in your controllers

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    #below gets the age of a post by subtracting a std time from its created_at time
    #a standard time in thsi context is called an epoch
    #dividen the distance in seconds since the epoch by the num of seconds in a day. this gives us the age in days.
    age_in_days = (self.created_at - Time.new(1970,1,1)) / (60 * 60 * 24) #1 day in seconds 
    
    #add the points (sum of the votes) to the age. this means taht the passing of one day wil be equiv to one down vote
    new_rank = points + age_in_days

    update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(value: 1, post: self)
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy

    scope :visible_to, -> (user) {user ? all : where(public: true)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  def index
    @posts = Post.all
    authorize @posts
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
    authorize @post
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
    if @post.save
      @post.create_vote
      flash[:notice] = "Post was saved"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error. Try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error. Please try again"
      render :edit
    end
  end

   def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 3)
  end

  def create
    @topic = Topic.new(params.require(:topic).permit(:name, :description, :public))
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully"
    else
      flash[:error] = "Error creating topic. Please try again"
      render :new
    end

  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(params.require(:topic).permit(:name, :description, :public))
      redirect_to @topic, notice: "Topic updated successfully"
    else
      flash[:error] = "Error in updating topic. Please try again"
      render :new
    end

  end

  def destroy
     @topic = Topic.find(params[:id])
 
     authorize @topic
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to topics_path
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/topics/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
<!-- add error handling here, which all all organized under ONE div class which is "alert alert-danger"-->
 <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %> <!-- array of error messages --> 
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
<!-- add blocks in lieu of the divs here... where it calls class 'form-group has-error' if there's an error and 'form-group' if there's no error.. use the helper method here where it takes a list of errors and a block-->
  <%= form_group_tag(post.errors[:title]) do %>
   <%= f.label :title %>
   <%= f.text_field :title, class: 'form-control', placeholder: 'anything cool?' %>
  <% end %>

  <%= form_group_tag(post.errors[:body]) do %>
   <%= f.label :body %>
   <%= f.text_area :body, class: 'form-control', placeholder: 'add some details here' %>
  <% end %>

  <div class='form-group'>
   <%= f.submit "Save", class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/topics/posts/edit.html.erb
<h1> Edit Post </h1>

<div class='row'>
  <div class='col-md-4'>
    <p> Guidelines for Posts </p> 
    <ul>
      <li> make sure it rhymes </li>
      <li> don't use the letter "A" </li>
      <li> the incessant use of hashtags will get you #banned </li>
    </ul>
  </div>
<div class='col-md-8'> 

  <%= render partial: 'form', locals: {topic: @topic, post: @post }%>

</div>
</div> 

app/views/topics/posts/new.html.erb
<h1> New Post </h1>

<div class='row'>
  <div class='col-md-4'>
    <p> Guidelines for Posts </p> 
    <ul>
      <li> make sure it rhymes </li>
      <li> don't use the letter "A" </li>
      <li> the incessant use of hashtags will get you #banned </li>
    </ul>
  </div>
<div class='col-md-8'> 
  
  <%= render partial: 'form', locals: {topic: @topic, post: @post} %>
</div>
</div>

app/views/topics/posts/show.html.erb
<!-- call the markdown_to_html method on string/text arguments to convert it to html
  ensure that you do this in posts/show as well in order to for it to parse the titles
-->

<div class = "row" >
  <div class = "col-md-8">
      <div> <%= render partial: 'votes/voter', locals: {post: @post}%> </div>
      <h1> <%= markdown_to_html @post.title %> </h1>
      <small>
        <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
        submitted <%= time_ago_in_words(@post.created_at) %> ago by
        <%= @post.user.name %>
      </small>
    <p> <%= markdown_to_html @post.body %> </p>
     <div class='js-comments'>
    <div class="media-body">
      <% @comments.each do |comment| %>
        <%= render partial: 'comments/comment', locals: {comment: comment }%>
      <% end %>
    </div>

    </div>
 <div class='new-comment'>
    <%= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @post.comments.new} %>
 </div>
  </div>
</div>

  <% if policy(@post).destroy? %>
    <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-warning'%>
  <% end %>
  
  <% if policy(@post).destroy? %>
    <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
  <% end %>

  <div>
    <h3> <%= pluralize(@post.points, 'point') %></h3>
    <small>
      <%= pluralize(@post.up_votes, 'up vote') %>,
      <%= pluralize(@post.down_votes, 'down vote') %>
    </small>
  </div>
  <%= render partial: 'favorites/favorite', locals: {post: @post} %>